name : test
on: [push, pull_request, workflow_dispatch]
jobs:
  testing-code:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3.0.0
    - run: python3 test.py
